data:
  task: binary
para:
  loss_type: l2_orth
  alpha: 0
  ori: false
  dropout: 0.2
  asr_alpha: 0.1
  iepa_alpha: 1
  cfus_alpha: 1
opt:
  name: Adam
  lr: 0.0009
  weight_decay: 5.0e-05
sche:
  name: SVFENDLR
num_epoch: 5
batch_size: 128
seed: 2024
model: SVFEND
dataset: FakeTT
type: 5-fold
patience: 3
name: SVFEND
freeze_gate: null
tex: false
cfg: SVFEND_FakeTT
task: binary